api:
  dashboard: true
  insecure: true
providers:
  docker:
    exposedByDefault: false
log:
  level: INFO
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
certificatesResolvers:
  myresolver:
    acme:
      email: carlton.joseph@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 0
